#!/usr/bin/julia

using Baozi

function main()
    if length(ARGS)==0||ARGS[1]=="help"
        print("""
            \e[1;39mBaozi --A static site generator in pure Julia\e[0m

            Baozi supports LaTeX by mathjax, and slides by revealjs
            \e[1;39m===========\e[0m
            Options:

            generate: generate slides
            *\e[1;33m new\e[0m: use `new xxx` to create new files
            *\e[1;33m publish\e[0m: publish slide to origin master
            *\e[1;33m publish=gh-pages\e[0m: publish slide to origin gh-pages
            *\e[1;33m init\e[0m : init a directory\n
            """)
    else
        for i in ARGS
            if i == "generate"
                gen()
            elseif i == "post"
                cp("_posts/example.md","_posts/$(next(ARGS,i)[2]).md")
            elseif i == "slide"
                cp("_slides/slide.md","_slides/$(next(ARGS,i)[2]).md")
            elseif i == "publish"
                run(`git push origin master`);
            elseif i=="publish=gh-pages"
                try 
                    run(`git checkout -b gh-pages`)
                catch
                    run(`git checkout gh-pages`)
                end
                run(`git push origin gh-pages`);
                run(`git checkout master`)
            elseif i=="init"
                try
                    mkdir("$(next(ARGS,i)[2])")
                catch
                    error("dir exists!\n")
                end
                cd("$(next(ARGS,i)[2])");
                init(pwd())
            else
                error("Do not have this command\n")
            end
        end
    end
end