#!/usr/bin/julia

using Baozi

function main()
    if length(ARGS)==0||ARGS[1]=="help"
        print("""
            \e[1;39mBaozi --A static site generator in pure Julia\e[0m

            Baozi supports LaTeX by mathjax, and slides by revealjs
            \e[1;39m===========\e[0m
            Options:

            *\e[1;33m generate\e[0m: generate slides
            *\e[1;33m post\e[0m: use `post xxx` to create new posts
            *\e[1;33m slide\e[0m: use `slide xxx` to create new slides
            *\e[1;33m publish\e[0m: publish slide to origin master
            *\e[1;33m publish=gh-pages\e[0m: publish slide to origin gh-pages
            *\e[1;33m init\e[0m : init a directory\n
            """)
    else
        i=1
        while i<=length(ARGS)
            if ARGS[i] == "generate"
                gen()
                i+=1
            elseif ARGS[i] == "post"
                cp("_posts/example.md","_posts/$(ARGS[i+1]).md")
                i+=2
            elseif ARGS[i] == "slide"
                cp("_slides/slide.md","_slides/$(ARGS[i+1]).md")
                i+=2
            elseif ARGS[i] == "publish"
                run(`git push origin master`);
                i+=1
            elseif ARGS[i]=="publish=gh-pages"
                try 
                    run(`git checkout -b gh-pages`)
                catch
                    run(`git checkout gh-pages`)
                end
                run(`git push origin gh-pages`);
                run(`git checkout master`)
                i+=1
            elseif ARGS[i]=="init"
                init(ARGS[i+1])
                i+=2
            else
                error("Do not have this command\n")
            end
        end
    end
end

main()